[[module.imports]]
path = "github.com/hugomods/seo/modules/alternative"

[[module.imports]]
path = "github.com/hugomods/seo/modules/base"

[[module.imports]]
path = "github.com/hugomods/seo/modules/favicons"

[[module.imports]]
path = "github.com/hugomods/seo/modules/json-ld"

[[module.imports]]
path = "github.com/hugomods/seo/modules/open-graph"

[[module.imports]]
path = "github.com/hugomods/seo/modules/schema"

[[module.imports]]
path = "github.com/hugomods/seo/modules/translations"

[[module.imports]]
path = "github.com/hugomods/seo/modules/twitter-cards"
